app:
  name: Ecommerce
  url: ${APPLICATION_URL:http://127.0.0.1:8080}
spring:
  profiles:
    active: {PROFILE:DEV}
  application:
    name: ecommerce
  config:
    import: optional:file:.env-dev[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL}jdbc:postgresql://localhost:5432/ecommerce
    username: ${SPRING_DATASOURCE_USERNAME:ecommerce_user}
    password: ${SPRING_DATASOURCE_PASSWORD:ecommerce_password}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  docker:
    compose:
      file: ./run/postgres-dev.yml
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger