version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: postgres_ecommerce
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  ecommerce_app:
    build: ./../
    image: ecommerce:dev
    container_name: ecommerce_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "9901:8080"
    depends_on:
      - postgres
    networks:
      - ecommerce_network
volumes:
  postgres_data:

networks:
  ecommerce_network: